### ISSUE TITLE
Error while running cleanup

### ISSUE THREAD

**Issue by bregman-arie** [yazug/shade_janitor#30]
Command: janitor.py --cloud my_cloud --cleanup

Traceback (most recent call last):
  File "./janitor.py", line 143, in <module>
    cleanup_resources(cloud, cleanup, dry_run=False)
  File "/home/abregman/dev/shade_janitor/shade_janitor/cleanup.py", line 142, in cleanup_resources
    cloud.remove_router_interface(router, uuid)
  File "/tmp/janitor4/lib/python2.7/site-packages/shade/openstackcloud.py", line 1887, in remove_router_interface
    _tasks.RouterRemoveInterface(router=router['id'], body=body)
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/janitor4/lib/python2.7/site-packages/shade/_utils.py", line 543, in neutron_exceptions
    "{msg}: {exc}".format(msg=error_message, exc=str(e)))
shade.exc.OpenStackCloudResourceNotFound: Error detaching interface from router a73744a7-75c9-43fa-9853-29774a104be1: Router a73744a7-75c9-43fa-9853-29774a104be1 has no interface on subnet 65619c6f-f1d1-4c8f-9fba-7363ccfc2af7
Neutron server returns request_ids: ['req-e17ccafa-34bf-4f4a-8f5f-728f60ced656']

**Comment by yazug** [comment]
I have seen this happen when janitor was not able to select all the resources, or if it tries to delete a resource it can't control.  Also this form of the command is the --Armageddon option (blow it all away)

**Comment by yazug** [comment]
If you see something like this or have more context as to the resource names it was trying to clean up it would be useful.  Otherwise will have to close this as can not reproduce.
